//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiSAv3.Client {
    
    
    public partial class MyReservation {
        
        /// <summary>
        /// DayPilotNavigator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DayPilot.Web.Ui.DayPilotNavigator DayPilotNavigator1;
        
        /// <summary>
        /// DayPilotCalendarDay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DayPilot.Web.Ui.DayPilotCalendar DayPilotCalendarDay;
        
        /// <summary>
        /// DayPilotCalendarWeek control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DayPilot.Web.Ui.DayPilotCalendar DayPilotCalendarWeek;
        
        /// <summary>
        /// DayPilotMonth1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DayPilot.Web.Ui.DayPilotMonth DayPilotMonth1;
    }
}
